apiVersion: v2
name: guestbook
description: A simple guestbook application using Nginx
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - guestbook
  - nginx
maintainers:
  - name: DevOps Team
