apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "guestbook.fullname" . }}-presync
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "10"]
      restartPolicy: Never